ports:
  - port: 8000
    visibility: public
    onOpen: ignore
  - port: 8080
    visibility: private
    onOpen: ignore
  - port: 1025
    visibility: private
    onOpen: ignore
  - port: 8025
    visibility: private
    onOpen: ignore

tasks:
  - command: |
      docker compose up --quiet-pull -d
      until docker compose exec wp-cli wp db check; do
        echo "Retrying in 5 seconds..."
        sleep 5;
      done
      docker compose exec wp-cli /bin/bash -c '\
        wp core install \
          --url="'$(gp url 8000)'" \
          --title="${WORDPRESS_SITE_NAME}" \
          --admin_user="${WORDPRESS_ADMIN_USER}" \
          --admin_password="${WORDPRESS_ADMIN_PASSWORD}" \
          --admin_email="${WORDPRESS_ADMIN_EMAIL}"\
      '
      docker compose exec wp-cli wp plugin activate wp-mailhog-smtp
      if test $? -eq 0; then
        printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' '#'
        echo '###'
        echo "###  Wordpress: $(gp url 8000)"
        echo "###  phpMyAdmin: $(gp url 8080)"
        echo "###  MailHog: $(gp url 8025)"
        echo '###'
        printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' '#'
      fi
      echo

vscode:
  extensions:
    - ms-azuretools.vscode-docker
