version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_HOST: db

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: supersecretpassword

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ./mailhog.php:/var/www/html/wp-content/plugins/wp-mailhog-smtp/mailhog.php
    working_dir: /var/www/html

  wp-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    restart: always
    user: 33:33
    environment:
      HOME: /tmp
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin
      WORDPRESS_ADMIN_EMAIL: foo@bar.com
      WORDPRESS_SITE_NAME: Wordpress on GitPod
    command: /bin/sh -c 'echo "Staying alive..."; tail -f /dev/null'
    volumes_from:
      - wordpress
    working_dir: /var/www/html

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  database:
  wordpress:
